# Site settings
title: Edi Santoso
description: 'Python & Odoo Developer who drink tea to enjoying the life'
url: 'https://me.repodevs.com'
enforce_ssl: 'me.repodevs.com'
baseurl: ''
slogan: '( @repodevs )'
disqus_shortname: 'repodevs'
google_analytics: 'UA-69004355-4'
img_url: '/assets/images'

author:
  name: 'Edi Santoso'
  email: repodevs@gmail.com
  twitter_username: repodevs
  facebook_username: repodevs
  github_username:  repodevs
  linkedin_username:  repodevs

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

# Extra Config
timezone: Asia/Jakarta
